import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "aos/dist/aos.css";

import PageWrapper from "@/components/PageWrapper";
import "./../globals.css";
import AOSProvider from "./Components/AOSProvider";
import Navbar from "./Components/Shared/Navbar/Navbar";
import BackToTop from "./Components/BackToTop";
import Footer from "./Components/Shared/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BU CSE Club",
  description: "Generated by create next app",
  icons: {
    icon: "/CSE_Club_Logo.png", // or "/favicon.png"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AOSProvider />
        <Navbar />
        <PageWrapper>
          <main className="min-h-screen">{children}</main>
        </PageWrapper>
        <BackToTop />
        <Footer />
      </body>
    </html>
  );
}
